
function json(res, status, body) {
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.end(JSON.stringify(body));
}

function method(req) {
  return String(req.method || "GET").toUpperCase();
}

async function readBody(req) {
  if (req.body && typeof req.body === "object") return req.body;
  let raw = "";
  for await (const chunk of req) raw += chunk;
  if (!raw) return {};
  try { return JSON.parse(raw); } catch { throw new Error("JSON inválido."); }
}

function env(name) {
  const value = process.env[name];
  if (!value) throw new Error(`Variável de ambiente ausente: ${name}`);
  return value;
}

async function redisCommand(command) {
  const url = env("UPSTASH_REDIS_REST_URL").replace(/\/+$/, "");
  const token = env("UPSTASH_REDIS_REST_TOKEN");
  const r = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify(command)
  });
  const text = await r.text();
  let data = {};
  try { data = JSON.parse(text); } catch {}
  if (!r.ok || data.error) {
    throw new Error(data.error || `Redis HTTP ${r.status}`);
  }
  return data.result;
}

async function redisGet(key) {
  const result = await redisCommand(["GET", key]);
  return result == null ? null : result;
}

async function redisSet(key, value) {
  return redisCommand(["SET", key, typeof value === "string" ? value : JSON.stringify(value)]);
}

async function redisDel(key) {
  return redisCommand(["DEL", key]);
}

async function redisLRange(key, start=0, stop=-1) {
  return redisCommand(["LRANGE", key, start, stop]);
}

async function redisRPush(key, value) {
  return redisCommand(["RPUSH", key, typeof value === "string" ? value : JSON.stringify(value)]);
}

async function redisDecrBy(key, amount) {
  return redisCommand(["DECRBY", key, amount]);
}

function parseJsonValue(value, fallback) {
  if (value == null) return fallback;
  if (typeof value !== "string") return value;
  try { return JSON.parse(value); } catch { return fallback; }
}

function cookie(req, name) {
  const raw = req.headers?.cookie || "";
  const found = raw.split(";").map(x => x.trim()).find(x => x.startsWith(name + "="));
  return found ? decodeURIComponent(found.slice(name.length + 1)) : "";
}

async function requireAdmin(req) {
  // Compatible with the admin-session endpoint used by the SQM frontend.
  // If SQM_ADMIN_SESSION_SECRET is configured, the cookie must match the
  // SHA-256 HMAC-style session value generated by your login endpoint.
  // For an existing deployment that already has /api/admin-session,
  // set SQM_ADMIN_SESSION_KEY to the same server-side session key.
  const session = cookie(req, "sqm_admin_session");
  const expected = process.env.SQM_ADMIN_SESSION_KEY;
  if (!session || !expected || session !== expected) {
    const err = new Error("Não autorizado.");
    err.statusCode = 401;
    throw err;
  }
  return true;
}

function parseOrders(values) {
  return (values || []).map(v => parseJsonValue(v, null)).filter(Boolean);
}

module.exports = async function handler(req, res) {
  try {
    await requireAdmin(req);

    if (method(req) === "GET") {
      const values = await redisLRange("sqm:pedidos", 0, -1);
      const orders = parseOrders(values).reverse();
      return json(res, 200, {orders});
    }

    const body = await readBody(req);
    const orderId = String(body.orderId || "").trim();
    if (!orderId) return json(res, 400, {error:"orderId obrigatório."});

    const values = await redisLRange("sqm:pedidos", 0, -1);
    const orders = parseOrders(values);
    const index = orders.findIndex(o => String(o.id) === orderId);
    if (index < 0) return json(res, 404, {error:"Pedido não encontrado."});

    if (method(req) === "PATCH") {
      const status = String(body.status || "").trim();
      if (!status) return json(res, 400, {error:"Status obrigatório."});
      orders[index] = {...orders[index], status, updatedAt:new Date().toISOString()};
    } else if (method(req) === "DELETE") {
      orders.splice(index, 1);
    } else {
      return json(res, 405, {error:"Método não permitido."});
    }

    await redisCommand(["DEL","sqm:pedidos"]);
    for (const order of orders) await redisRPush("sqm:pedidos", order);

    if (method(req) === "DELETE") {
      await redisDel(`sqm:order:${orderId}`);
      return json(res, 200, {ok:true});
    }

    await redisSet(`sqm:order:${orderId}`, orders[index]);
    return json(res, 200, {ok:true, order:orders[index]});
  } catch (e) {
    console.error("SQM orders:", e);
    return json(res, Number(e.statusCode || 500), {error:e.message || "Erro nos pedidos."});
  }
};
